# GitHub Pages 配置文件
include:
  - .well-known

# 其他配置
plugins:
  - jekyll-sitemap
  - jekyll-feed

# 网站信息
title: "Liangjie's Blog"
subtitle: "Welcome to a place of thinker"
description: "个人技术博客，分享编程经验和技术心得"
url: "https://joeljay.github.io"
baseurl: ""

# 作者信息
author:
  name: "Joel"
  email: "huangliangjie110@163.com"

# 社交媒体
social:
  github: "joeljay"
  twitter: "your_twitter"
  linkedin: "your_linkedin"

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _drafts

# 集合
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# 分页
paginate: 10
paginate_path: /page:num/

# 默认布局
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 时区
timezone: Asia/Shanghai

# 语言
lang: zh-CN