# GitHub Pages 配置文件
include:
  - .well-known

# 其他配置
plugins:
  - jekyll-sitemap
  - jekyll-feed

# 网站信息
title: "我的GitHub Pages"
description: "这是我的GitHub Pages个人网站"
url: "https://joeljay.github.io"
baseurl: ""

# 作者信息
author:
  name: "Joel Jay"
  email: "your.email@example.com"

# 社交媒体
social:
  github: "joeljay"
  twitter: "your_twitter"
  linkedin: "your_linkedin"

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
